name: GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: AlanDiogoR

          # VISUAL
          template: classic
          config_theme: carbon
          config_timezone: America/Sao_Paulo
          config_display: regular
          config_padding: 10

          # BASE (IMPORTANTE)
          base: header,activity,languages,repositories

          # STREAK REAL
          plugin_streak: yes
          plugin_streak_days: yes
          plugin_streak_limit: 21

          # ATIVIDADE
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 14
          plugin_activity_visibility: all

          # LINGUAGENS (CORREÇÃO PRINCIPAL)
          plugin_languages: yes
          plugin_languages_limit: 6
          plugin_languages_sections: most-used
          plugin_languages_details: percentage
          plugin_languages_colors: github
