name: GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *" # todo dia
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: AlanDiogoR

          # ðŸŽ¨ Visual (estilo radical)
          template: classic
          config_timezone: America/Sao_Paulo
          config_display: large
          config_padding: 0

          # ðŸ§± Base
          base: header,activity,community,repositories

          # ðŸ”¥ STREAK (sequÃªncia de commits)
          plugin_streak: yes
          plugin_streak_days: yes
          plugin_streak_limit: 30

          # ðŸ“Š Activity
          plugin_activity: yes
          plugin_activity_limit: 10
          plugin_activity_days: 14
          plugin_activity_visibility: all

          # ðŸ“ˆ Languages (combina com seu README)
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_colors: github
          plugin_languages_details: bytes-size, percentage

          # ðŸŸ£ Tema escuro (combina com radical)
          config_theme: dark
